### ISSUE TITLE
BRs: Clarify the relationship between id-kp-clientAuth, BR Policy OIDs, and the Scope of the BRs

### ISSUE THREAD

**Issue by sleevi** [cabforum/servercert#196]
The profile for Subscriber Certificates, in 7.1.2.3, currently permits the values `id-kp-serverAuth`, `id-kp-clientAuth`, as well as any other policies:

https://github.com/cabforum/documents/blob/d9b360f15d6ce3079c735e69539666e09b0c85e7/docs/BR.md#L1668

@dougbeattie raised a question in the 2020-06-18 Validation WG call as to whether it's required for a certificate to assert `id-kp-serverAuth` if it is going to assert one of the CA/Browser Forum Reserved Policies, established in Sections 1.2 and Sections 7.1.6.1.

The discussion included analyzing how a certificate issued to a server could contain ONLY `id-kp-clientAuth`, assert a DV OID, and be used for server-to-server mutual authentication, where server means "hostname" or "service", raising a question whether that was in scope of Section 1.1:

https://github.com/cabforum/documents/blob/d9b360f15d6ce3079c735e69539666e09b0c85e7/docs/BR.md#L30

Or whether such certificates were out of scope, by virtue of TLS still having a notion of client and server, and such server-to-server authentication may not be in scope, either by virtue of the protocol or by virtue of the EKU.

Fundamental questions that came up:
1. If a certificate ONLY asserts `id-kp-clientAuth`, and is issued from an in-scope subordinate, is that certificate in scope of the BRs?
2. If a certificate ONLY asserts `id-kp-clientAuth`, and asserts a BR OID, is that certificate in scope of the BRs?
3. Is the scope of the BRs defined by what asserts the CABF OIDs, what EKUs are asserted, or some combination thereof?
4. If it's by EKUs asserted, does the `id-kp-clientAuth` EKU fit within the scope, as it applies to asserting the CABF OIDs?

**Comment by sleevi** [comment]
@cbonnell @timfromdigicert

**Comment by sleevi** [comment]
My proposal:
* Require id-kp-serverAuth for Subscriber Certificates
* Require that asserting a policy OID MUST match a defined certificate profile for that policy OID

This would mean:
* If the Intermediate Certificate asserts `id-kp-clientAuth` and `id-kp-serverAuth` (permitted by BRs) and has either `anyPolicy` or asserts a CABF OID
* And it issues an `id-kp-clientAuth` cert asserting a BR policy OID
* Then it would be missuance

* If the Intermediate Certificate asserts `id-kp-clientAuth` and `id-kp-serverAuth` and has either `anyPolicy` or asserts a CABF OID
* And it issues an `id-kp-clientAuth` cert that does NOT assert a BR policy OID
* Then it would NOT be misissuance

**Comment by timfromdigicert** [comment]
I think you meant to imply in your examples that the certificate has id-kp-clientAuth ONLY, and specifically does not have id-kp-serverAuth.  With that clarification, which I'm pretty sure you meant anyway, I agree that your examples are a reasonable path forward (though potentially not the only one).

The consensus two weeks ago was that BR certificates that don't contain id-kp-serverAuth was more of a bug in the current BRs rather than a feature.

**Comment by sleevi** [comment]
> I think you meant to imply in your examples that the certificate has id-kp-clientAuth ONLY, and specifically does not have id-kp-serverAuth. 

Could you quote-reply what you think is ambiguous? The examples mention that?

**Comment by timfromdigicert** [comment]
It depends what is meant by "issues an id-kp-clientAuth cert".  One reading (the one I believe you meant, and which makes the most sense in these examples) is that id-kp-clientAuth is the only EKU in the cert.  But "an id-kp-clientAuth cert" can also mean a certificate that has id-kp-clientAuth, but also may have other EKUs.  For example, under normal usage, I'd consider a id-kp-clientAuth + id-kp-serverAuth to be "an id-kp-clientAuth cert", but that interpretation doesn't work here.

**Comment by sleevi** [comment]
I'm still having trouble figuring out what you meant, are you talking about https://github.com/cabforum/documents/issues/196#issuecomment-646138803 ? I've gone and fixed that to be unambiguous, but it was (and is) a little unclear whether you're talking about that or referring to something in https://github.com/cabforum/documents/issues/196#issue-641339990

You can use the little dots on the top right reply to do a quoted reply and make it clearer :)

**Comment by timfromdigicert** [comment]
You fixed the examples correctly to resolve the ambiguity I was highlighting.

**Comment by CBonnell** [comment]
I don't see how clarifying this relationship in the BRs helps, because Root Programs do not mandate compliance to the BRs for any end-entity certificates that are technically constrained such that they cannot be used for server authentication (i.e., no serverAuth in the EKU). This is readily apparent in section 1.1 of Mozilla Root Policy, which explicitly excludes clientAuth-only certificates from Mozilla Root Program requirements scope.

Given that the requirement for CAs to adhere to the BRs is a function of Root Program requirements mandating such adherence,  I believe this prohibition on clientAuth-only certs expressing CABF Policy OIDs needs to be expressed in the individual Root Program requirements, as the BRs currently have no normative force for non-serverAuth certificates.

**Comment by techliaison** [comment]
Corey - the BRs define the policy OIDs so it is appropriate for the BRs to clarify when they can be asserted in certificates and when they should not be asserted.

**Comment by sleevi** [comment]
@CBonnell Several implementations accept *only* `id-kp-clientAuth` when validating a TLS peter precisely because of the S2S auth case.

While I can understand your disagreement, I think you are overlooking an important perspective, which is at the heart of this issue. Your reply is simply advocating that scope is entirely EKU based, and only EKU based. However, as policy OIDs are defined, both in 5280 and within the BRs themselves, policy OIDs are explicitly intended to bring something into scope.

There’s little disagreement that lacking both EKU and OID are out of scope. There’s also little disagreement that having a `serverAuth` EKU but lacking policy OID is in scope, specifically because clients will accept those certificates even without the policy OID. The matter for clarification is whether including the policy OID, and without a `serverAuth` EKU Is also in scope, precisely again because clients may accept this.

**Comment by sleevi** [comment]
To consider why this is important:

Imagine a world where a root store defined a root store specific Policy OID that all certificates in its program must possess. It inhibited `anyPolicy`, and made use of Policy Mappings for each CA included in its root program, to map that CAs policies (or the common BR policies) onto that Root Program specific OID.

In such a model, the EKU would be entirely ignored for intermediates, which is closer to the definition in RFC 5280. Any intermediate asserting a mapped policy OID would be in scope (Especially as anyPolicy is inhibited), and any leaf they issue would be in scope if they asserted a policy OID. This is the model of PKI that 5280 was designed to accommodate, and avoids CA’s confusion and concerns over EKU chaining. In this model, scope is solely defined by policy OID.

This is why it’s important *now* to clarify the scope and relationship, and whether a CA asserting a policy OID brings something in scope. If the answer is no, then the scenario I just described is not possible to safely deploy or transition to. If the answer is yes, you’re in scope if you assert this policy OID, which as Wendy points out is an entirely reasonable thing to do, then it is a deployable model.

**Comment by CBonnell** [comment]
> Your reply is simply advocating that scope is entirely EKU based, and only EKU based.

I am not advocating that this is the preferred end state, but rather a statement on the requirements of several Root Programs as they stand today. Root Program requirements currently delineate scope by only the EKU value and there is no interplay with Policy OIDs. As mentioned before, Mozilla policy section 1.1 is an example of this.  Therefore, for the BRs to have any normative force on the profile of non-serverAuth certificates, Root Program requirements need to be modified such that non-serverAuth certificates that express the CABF Policy OIDs need to comply with the BRs.

I fully understand the motivation and end goal here, but I believe there's work to be done at the individual Root Program level to expand their scopes such that all certificates (regardless of EKU) that express the CABF OIDs need to comply with the BRs.

**Comment by sleevi** [comment]
> I fully understand the motivation and end goal here, but I believe there's work to be done at the individual Root Program level to expand their scopes such that all certificates (regardless of EKU) that express the CABF OIDs need to comply with the BRs.

It’s unclear how that is germane or relevant to this issue.

Consider if a Root Program changed today to make that assertion. Even with that change, it would still be ambiguous in the BRs, and thus ambiguous if it’s a root program violation. Nothing of substance is solved.

Consider if we address this issue, as proposed, and no Root Program changed. It would get folded into the audit scope and become a matter on any BR audit, and transitively so. That alone is valuable.

You seem to be worrying about the scope for CAs that do not have BR audits today, but are still subject to Root Program requirements. I agree, that’s interesting, but I don’t think that’s germane to this issue. That’s something for Root Programs to sort, and is trivially done.

**Comment by CBonnell** [comment]
> It’s unclear how that is germane or relevant to this issue.

Here's a concrete scenario that maybe helps to address the disconnect: a publicly trusted intermediate with serverAuth and clientAuth EKU issues a clientAuth-only end-entity certificate with a common name of "Ryan Sleevi".

Is this currently a Root Program policy violation, as the CN is clearly not a valid hostname?

I'd argue that it is not, because Root Programs do not mandate adherence to the certificate profile in the BRs for certificates not expressing the serverAuth EKU (again, see Mozilla Root Policy sections 1.1 and 2.3). This is why it is important for Root Programs to be amended to expand their scope to encompass policy OIDs, otherwise any changes in the BRs in regard to non-serverAuth certificates have no normative force.

**Comment by sleevi** [comment]
> Is this currently a Root Program policy violation, as the CN is clearly not a valid hostname?

And this issue is trying to track that you can make a clear argument, that yes, the intermediate, by asserting the BR policy OID, but not having validated the certificate to the BRs, has violated the BRs.

The normative force already exists *on the intermediate*, but it's ambiguous at present whether the scenario you raise is a *BR* violation or not. The scoping issue you describe re: Root Programs is a red herring. If the intermediate makes the Subscriber Certificate subject to the BRs, and the Subscriber Certificate does not comply with the BRs, the BR violation happened *at the intermediate*.

The disconnect is in trying to think only of the Subscriber certificate in isolation, which doesn't make sense, because every Subscriber certificate is issued by an Issuing Certificate.

This is no different than if an Intermediate CA, **capable of causing issuance**, issued a non-RFC 5280 certificate (e.g. with subject name attributes outside the length requirements specified by RFC 5280). If the intermediate is subject to the BRs, it doesn't matter if that Subscriber certificate "isn't intended" to be a server certificate. It's the act of issuance that is the BR violation, and that's based on the Intermediate being in scope, not by the Subscriber being in scope.

Put differently:
* If the intermediate asserts *both* `id-kp-clientAuth` AND `id-kp-serverAuth` and asserts a CABF OID
* And the Subscriber *only* asserts `id-kp-clientAuth` AND asserts a CABF OID
Then it's a violation

However,
* If the Intermediate *only* asserts `id-kp-clientAuth` AND asserts a CABF OID
* And the Subscriber certificate *only* asserts `id-kp-clientAuth` AND asserts a CABF OID
Then it's dependent on the Root Program scope

The proposal I set out would resolve this asymmetry, by saying:
* If you assert the CABF OID, you are subject to the BRs

This means if asserted within an intermediate, it's subject. If asserted within a Subscriber certificate, it's subject.

Now, there's still matters at play with `anyPolicy`, which is why I described somewhat the end-state goal.

**Comment by CBonnell** [comment]
>The scoping issue you describe re: Root Programs is a red herring. If the intermediate makes the Subscriber Certificate subject to the BRs, and the Subscriber Certificate does not comply with the BRs, the BR violation happened at the intermediate.

This framing is not supported by the defined scope of at least the Mozilla Root Program. We can see from section 1.1 (3) that scope covers only those end-entity certificates which express no EKU, anyEKU, or serverAuth EKU (I'll call these three possible values "NAS" for conciseness). If the intent were to capture all issuance/signing operations performed with the CA private key as being in scope of the BRs by virtue of the NAS being expressed in the CA certificate, then 1.1 (3) needs to be updated to clearly state that all issuance from a CA in scope as defined 1.1 (2) is in scope of policy. That however, is not the current interpretation taken by Mozilla (see below).

> The disconnect is in trying to think only of the Subscriber certificate in isolation, which doesn't make sense, because every Subscriber certificate is issued by an Issuing Certificate.

It makes perfect sense when looking at the previous discussions and issues. Last year, one CA in the Mozilla Root Program was issuing end-entity certificates with no EKU in any of the certificates in the path and the accepted remediation was to add an appropriate EKU in the end-entity certificates to exclude them from Mozilla scope. However, according to your "mis-issuance at the intermediate level" interpretation, this is not sufficient, as the intermediates would be under BR scope by virtue of the lack of EKU and the end-entity certificates issued by this CA would be in violation of BR 7.1.2.3 (f) due to not including the requisite EKU(s).

Looking further back, we can see statements from Mozilla Representatives on the need for in-scope issuing CAs to have the ability to issue end-entity certificates that are out of scope of policy. The discussion at https://groups.google.com/d/topic/mozilla.dev.security.policy/leZRiBJ4Vqs/discussion is relevant here, and the comment https://groups.google.com/d/msg/mozilla.dev.security.policy/leZRiBJ4Vqs/l5IRD6QdBQAJ is particularly salient.

> This is no different than if an Intermediate CA, capable of causing issuance, issued a non-RFC 5280 certificate (e.g. with subject name attributes outside the length requirements specified by RFC 5280). If the intermediate is subject to the BRs, it doesn't matter if that Subscriber certificate "isn't intended" to be a server certificate. It's the act of issuance that is the BR violation, and that's based on the Intermediate being in scope, not by the Subscriber being in scope.

I suppose this might bring on a discussion of "is this a certificate?", but I believe it's reasonable to assert that issuance of certificate-shaped objects is a violation of Root Program policy (such as Mozilla Root Policy 5.2) and is not a BR violation per se because the tbsObject isn't a certificate.

**Comment by sleevi** [comment]
> I suppose this might bring on a discussion of "is this a certificate?", but I believe it's reasonable to assert that issuance of certificate-shaped objects is a violation of Root Program policy (such as Mozilla Root Policy 5.2) and is not a BR violation per se because the tbsObject isn't a certificate.

While I can appreciate the level of covering multiple interpretations, I hope we can agree that:
1. The discussion here (about what it means to root programs) is largely irrelevant to the discussion at hand here for what the BRs should say
2. That the above interpretation has itself been subject to debate in the past, both with respect to signatures in SIGNED-DATA constructs and specifically with respect to CT.

My worry is the disagreement we’re having on this issue, which largely seems to be unrelated to fixing the BRs and instead focusing on root store policies out of scope of the BRs, would end up distracting from addressing the issue we both can and should address here, and now.

**Comment by CBonnell** [comment]
> My worry is the disagreement we’re having on this issue, which largely seems to be unrelated to fixing the BRs and instead focusing on root store policies out of scope of the BRs, would end up distracting from addressing the issue we both can and should address here, and now.

I think this discussion is important and not a distraction, because it highlights that specifying the profile of non-serverAuth certificates in the BRs has no effect if Root Programs are not modified so that non-serverAuth end-entity issuance is in scope of their respective policies and/or the BRs. As it stands, this proposal has no normative force behind it, so it will not accomplish the goals outlined.

**Comment by sleevi** [comment]
> As it stands, this proposal has no normative force behind it, so it will not accomplish the goals outlined.

The BRs themselves have no normative force, so I cannot understand the point of stating that here.

The goal is to provide clarity about the scope so things are aligned, and to resolve the uncertainty if something is, to use your own framing (which I still believe is incorrect):
- Is something BR forbidden, but ignored by root programs
- Is something BR allowed, but forbidden by root programs

Again, I think the discussion of Root Program requirements to be quite inappropriate here, because the underlying issue exists independent of them and must still be solved. “Does asserting the BR OID make something subject to the BRs” is a question the BRs can, and necessarily should, take a position on, because it makes clearer requirements. Whether or not that BR violation is a root program violation is not germane to that.

**Comment by barrini** [comment]
F2F 60 decission to close
