### ISSUE TITLE
Revise the definition of Registration Authority 

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [cabforum/servercert#313]
Under “Registration Authority (RA):”  Replace the phrase, 

"When “RA” is used as an adjective to describe a role or function, it does not necessarily imply a separate body, but can be part of the CA.” 

with 

““RA” does not necessarily imply a separate body, but can be part of the CA.”

The rationale is that the conditions part of the definition for RA shouldn't apply only when "RA" is used as an adjective to describe a role or function. In any event, the final clause is just a clarification--that generally, RA doesn't imply a separate entity.  Alternatively, we could outline pure CA functions and pure RA functions and describe how they can be grouped together under the concept of "CA".

**Comment by RufusJWB** [comment]
You could have a look into [ETSI EN 319 411-1](https://www.etsi.org/deliver/etsi_en/319400_319499/31941101/01.03.01_60/en_31941101v010301p.pdf). On page 10 they have a definition of CA, on page 11 a definition of RA and on the page 16&17 a definition, how the different 'subservices' (RA, CA, ...) play together within a PKI environment. It might be worth copying this definition instead of re-inventing the wheel.

**Comment by BenWilson-Mozilla** [comment]
This isn't a critical edit to improving the Baseline Requirements.
