### ISSUE TITLE
Add linting requirements to the TLS BRs

### ISSUE THREAD

**Issue by clintwilson** [cabforum/servercert#443]
**Note**: The title is written as an imperative, but this is intended propose future work and capture discussion surrounding the topic. I would appreciate any input as to whether the assumptions and conclusions below are accurate, and what updates to the associated priors would increase their accuracy, based on the additional data available to CAs or other informed parties. Similarly, I couldn't find an issue that already addresses this, but let me know if I've missed something.

Linting has become a very important component of modern certificate issuance. While by no means immune to error as a technology, my understanding is that thorough and well thought out implementation of certificate linting has proven to be invaluable in detecting a wide variety of certificate misissuances (especially combined with the use of CT). Further, where implemented by CAs as an additional pre-issuance check it has prevented many more misissuances.

At this point, many CAs have encountered incidents for which implementation of linting was part of the remediation of identified root causes. In a fair number of cases, it was part of the remediation of multiple incidents. This leads me to a few conclusions:
1. Many CAs already have certificate-related linting functionality implemented within their CA infrastructure.
2. CAs that haven't implemented certificate-related linting should almost certainly do so (including future CAs that don't exist yet).
3. There is likely substantial variance in what, how, and when linting is performed by the CAs that currently perform certificate-related linting.

Combined, these conclusions further lead me to believe that it would be a valuable addition to the BRs to define minimally a requirement that CAs include linting as part of their certificate issuance processes. Beyond that, it seems potentially worthwhile to define with greater specificity some or all of the following:
* what should be linted (i.e. what data structures)
* how linting should be performed (e.g. what tools are recommended, required, or allowed, considering "well known" tools like zlint, x509lint, pkilint, and certlint/cablint)
* when linting should occur (e.g. after certificate request receipt, before and/or after tbsCertificate, precertificate, and final certificate generation, etc.)

My hope is that enough CAs have already implemented linting that this type of change would be:
1. well-informed by expertise stemming from deep experience;
2. data driven; and 
3. of low-ish impact overall across the industry as only a minority (🤞) of CAs would need to make substantial changes.

**Comment by robstradling** [comment]
> ...what tools are recommended, required, or allowed

I realise the SC59v2 ballot recently failed, but during the lengthy drafting period for that ballot there was a fair bit of discussion about whether or not it's appropriate for the BRs and/or CABForum to dictate and/or recommend particular tools.  AIUI the consensus was that (1) the BRs should merely link to https://cabforum.org/resources/tools/, and that (2) that page should neither dictate nor recommend any particular tool, but should merely list the available tools with no more than a brief description of each one.

Is it reasonable to assume that the consensus established during that previous discussion will apply to linters too?

**Comment by timfromdigicert** [comment]
I agree we avoid requiring specific linting tools.  There are a whole host of reasons why that is a bad idea, and I can explain further if anyone disagrees.

**Comment by romanf** [comment]
Absolutely agree. CAs might use their own (re-implementations) which would become non-compliant...

**Comment by dzacharo** [comment]
I am tempted to just "disagree" because I love your explanations :) Based on the number of CA incidents we should require some sort of pre-issuance linting in the BRs but not be overly perspective nor promoting specific "products".

**Comment by ryancdickson** [comment]
Would we consider encouraging the use of open-source tools over closed/proprietary solutions without going so far as requiring CAs to follow a specific approach?

Motivation: I appreciate the idea of a "write-once, use many" solution and its opportunity to amplify positive contributions across the ecosystem. For example, we might consider it "best practice" for a CA owner to contribute lints back to open source projects after mis-issuance, such that others are less likely to repeat the same issue.

[I know this is more complicated than it seems, but it seems like an admirable goal and will help reduce incident "noise" so the community can focus on high-value incidents with a clear impact on user security --- rather than "benign" mis-issuance.]

**Comment by timfromdigicert** [comment]
Darn.  It looks like it's Dimitris' lucky day, and I do have to explain further :)

Write the requirement for the objective you want.  Let CAs determine the best way to comply with the requirement.  For many CAs, working together on one or more open source projects will probably be the right answer, for exactly the reasons you describe.  However, if it's not the best answer for them, should we really force them to do what we think is best, instead of what they know is best for them?

We can save a lot of time and effort by not dragging the whole topic of whether open source is better or not into this.  I'll also quote from the CA/Browser Forum Bylaws:

"Members shall not use their participation in the Forum either to promote their own products and offerings or to restrict or impede the products and offerings of other Members."

I would say that requiring or even encouraging the adoption of specific software projects or that projects should follow a particular software development model comes dangerously close to violating such legal requirements.

**Comment by robstradling** [comment]
Without advocating the use of any particular technology, my advice to CAs is to consider using as many different linters as possible.  Although there's considerable overlap in the checks performed by each of the available linters, we've seen quite a few CA incidents where only a subset of the linters has caught a particular problem.  Indeed, some problems have only been spotted by a single linter.

Different linters have different strengths.

**Comment by romanf** [comment]
As a side note, we probably also should include a definition of "a linter" that differs from https://en.wikipedia.org/wiki/Lint_(software) as we're not looking for code-analysis but "data analysis".

**Comment by BenWilson-Mozilla** [comment]
Closing, as this has been addressed by Ballot SC-75.
